# Application Settings
server.port=8080

# Elasticsearch Settings
# 因为代码里写死了使用 HTTPS 构建 RestClient，这里如果是 HTTP 会报错，实际测试环境按需修改。
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.username=
elasticsearch.password=

# 基础 MySQL 配置 (目前留空，待 Stage 2 构建)
# spring.datasource.url=jdbc:mysql://localhost:3306/monitor_db?useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=123456
